version: '3.8'
services:
  api:
    image: datascientest/fastapi:1.0.0
    ports:
      - ${API_PORT}:${API_PORT}
    deploy:
        restart_policy:
            condition: on-failure
  test_authentication:
    build:
        context: .
        args:
          - CICD_STEP=authentication
    environment:
        - API_URL=${API_URL}
        - API_PORT=${API_PORT}
        - TEST_RESULT_PATH=${TEST_RESULT_PATH}
    volumes:
      - ./test_results:/app/test_results
    depends_on:
      - api
  test_authorization:
    build:
        context: .
        args:
          - CICD_STEP=authorization
    environment:
        - API_URL=${API_URL}
        - API_PORT=${API_PORT}
        - TEST_RESULT_PATH=${TEST_RESULT_PATH}
    volumes:
      - ./test_results:/app/test_results
    depends_on:
      - api
      - test_authentication
networks:
    default:
      driver: bridge

